global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "app-crud"
    metrics_path: '/actuator/prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: ["app-crud:8084"]

rule_files:
  - '/etc/prometheus/alert.rules.yml' 